const FormActionTypes = {
  SET_SELECTED: 'SET_SELECTED',
  FETCH_FORM_START: 'FETCH_FORM_START',
  FETCH_FORM_SUCCESS: 'FETCH_FORM_SUCCESS',
  FETCH_FORM_FAILURE: 'FETCH_FORM_FAILURE',
  SET_FORM: 'SET_FORM',
  ADD_FORM_ELEMENT: 'ADD_FORM_ELEMENT',
  REMOVE_FORM_ELEMENT: 'REMOVE_FORM_ELEMENT',
  CLEAR_FORM: 'CLEAR_FORM',
  SET_SCHEMA: 'SET_SCHEMA',
  ADD_SCHEMA_ELEMENT: 'ADD_SCHEMA_ELEMENT',
  REMOVE_SCHEMA_ELEMENT: 'REMOVE_SCHEMA_ELEMENT',
  CLEAR_SCHEMA: 'CLEAR_SCHEMA',
  SET_MODEL: 'SET_MODEL',
  ADD_MODEL_ELEMENT: 'ADD_MODEL_ELEMENT',
  REMOVE_MODEL_ELEMENT: 'REMOVE_MODEL_ELEMENT',
  CLEAR_MODEL: 'CLEAR_MODEL',
  SET_LAYOUTS: 'SET_LAYOUTS',
  ADD_LAYOUT_ELEMENT: 'ADD_LAYOUT_ELEMENT',
  REMOVE_LAYOUT_ELEMENT: 'REMOVE_LAYOUT_ELEMENT',
  CLEAR_LAYOUT_ELEMENTS: 'CLEAR_LAYOUT_ELEMENTS',
}

export default FormActionTypes
