export const FormElements = Object.freeze({
    number: 'Number',
    text: 'Text',
    password: 'Text',
    textarea: 'TextArea',
    markdown: 'Markdown',
    textsuggest: 'TextSuggest',
    select: 'Select',
    taxonomy: 'Taxonomy',
    radios: 'Radios',
    date: 'DateComponent',
    timestamp: 'Timestamp',
    checkbox: 'Checkbox',
    help: 'Help',
    array: 'Array',
    tBoolean: 'TripleBoolean',
    fieldset: 'FieldSet',
    tuple: 'FieldSet',
    multiselect: 'MultiSelect'
});