const GridActionTypes = {
  SET_ON_LAYOUT_CHANGE: 'SET_ON_LAYOUT_CHANGE',
  TOGGLE_SHOW_ERRORS: 'TOGGLE_SHOW_ERRORS',
  SET_ROW_HEIGHT: 'SET_ROW_HEIGHT',
  SET_BREAKPOINT: 'SET_BREAKPOINT',
  SET_COMPACT_TYPE: 'SET_COMPACT_TYPE',
  SET_COL_BREAKPOINTS: 'SET_COL_BREAKPOINTS',
  SET_ELEMENT_SELECTED: 'SET_ELEMENT_SELECTED',
}

export default GridActionTypes
